# Generated by Django 6.0 on 2026-01-06 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Karyawan')),
                ('position', models.CharField(choices=[('KASIR', 'Kasir'), ('GUDANG', 'Staff Gudang'), ('SUPIR', 'Supir/Driver'), ('ADMIN', 'Admin')], max_length=20, verbose_name='Jabatan')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='No HP')),
                ('basic_salary', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Gaji Pokok')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='Tanggal Bergabung')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Tanggal Pembayaran')),
                ('bonus', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Bonus')),
                ('deduction', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Potongan (Kasbon/Telat)')),
                ('total_amount', models.DecimalField(decimal_places=0, editable=False, max_digits=12, verbose_name='Total Diterima')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.employee', verbose_name='Karyawan')),
            ],
        ),
    ]
