# Generated by Django 6.0 on 2026-01-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_employee_salarypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Kategori'),
        ),
        migrations.RemoveField(
            model_name='salarypayment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='material',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='material',
            name='description',
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='Foto Barang'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nama Barang'),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.IntegerField(verbose_name='Harga (Rp)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='stock',
            field=models.IntegerField(verbose_name='Stok'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(max_length=50, verbose_name='Satuan (Sak/Pcs/M3)'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='SalaryPayment',
        ),
    ]
