# Generated by Django 6.0 on 2026-01-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_material_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Karyawan')),
                ('division', models.CharField(max_length=100, verbose_name='Divisi')),
                ('salary', models.IntegerField(verbose_name='Gaji (Salary)')),
            ],
        ),
    ]
